### ISSUE TITLE
アラートからトーストに変更する

### ISSUE THREAD

**Issue by omacchi** [KenyaSugimoto/RitsChiebukuro#158]
今のところ結構アラート出す仕組みにしてるけど、アラート出すWebサイトってそんなに多く無い？
何となく上/下からシュッって出てきて
自分がした動作(質問、コメント、回答とか)が完了したことや、これじゃ送信できませんとかを表示させる。
そして、何秒かたったらそれが消えるイメージ。

**Comment by omacchi** [comment]
何か他に良い方法もありそうやから、そこらへんも含めて、何が良さそうか検討して欲しい！

**Comment by omacchi** [comment]
全部動作完了させた後に一旦、一時的なページに遷移させて、操作反映後のページに飛ばすのはワンクリック多くなってしまうイメージ。動作完了したことは分かりやすいねんけどなー

**Comment by KenyaSugimoto** [comment]
賛成。
トーストのデメリットはユーザが画面見てなかったら気づかずに終わっちゃうところだけど、アラート使ってるところは基本的にボタン押した直後だからあり
