### ISSUE TITLE
textareaの改行を検知する

### ISSUE THREAD

**Issue by omacchi** [KenyaSugimoto/RitsChiebukuro#226]
現状、改行しても
質問詳細画面、一覧画面では改行が無視される

**Comment by KenyaSugimoto** [comment]
参考ページ
https://qiita.com/huigo/items/0efcf50c17b0b1ee27cb

**Comment by KenyaSugimoto** [comment]
CSS の white-space プロパティ 
https://developer.mozilla.org/ja/docs/Web/CSS/white-space
