### ISSUE TITLE
重複するユーザIDは登録できないようにする

### ISSUE THREAD

**Issue by KenyaSugimoto** [KenyaSugimoto/RitsChiebukuro#29]
#26 が終わったらね。

**Comment by omacchi** [comment]
ユーザIDというかユーザ名？
ユーザID (userUid)は一意になってる。

**Comment by KenyaSugimoto** [comment]
ユーザー名だな。
けど、これも英数字にした方が良くない？
Uidはあくまで裏で識別するためのIDで
ユーザ名はis0359fhとかomacchiみたいに表で見れるイメージ

**Comment by omacchi** [comment]
英数字にしてもいいと思うけど、
英数字に制限しなくていいとも思う

**Comment by omacchi** [comment]
idTokenが無いとusersテーブルにアクセスできない
一度アカウント登録させてidTokenを取得
usersテーブルを検索し、同じユーザ名があった場合、アカウントを削除し、警告を出す。
